services:
  cl2ns:
    image: ghcr.io/bigcheesesteak/cl2ns:latest
    container_name: cl2ns
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - cl2ns_data:/data

volumes:
  cl2ns_data:
